### ISSUE TITLE
[question] How to change publisher/developer in Package Center?

### ISSUE THREAD

**Issue by schumi2004** [mbirth/sspks#2]
Probably a stupid question but how do i change Publisher and Developer in Synology package center?
Currently it's showing SSpkS.

Thanks in advance.

**Comment by mbirth** [comment]
These are the fallback values for when there is no "distributor" or "maintainer" entry found in the package's INFO file. However, I think I found a bug with that. Will have to check it.

**Comment by mbirth** [comment]
I found the problem and fixed it over at https://github.com/jdel/sspks/tree/rework . Thanks for pointing me to it!
